- src/main/java/com/sds/actlongs/config/SwaggerConfig.java
- src/test/resources/application.yml
테스트 application.yml을 추가했어요.
- db는 h2 memory db를 사용해요.
Swagger 설정은 local, dev 환경에서만 적용하도록 했어요.
> 테스트 application.yml 추가 및 Swagger 설정 profile 분리

- src/main/java/com/sds/actlongs/domain/BaseEntity.java
- 리뷰 긴급도: D-x
공통 컬럼(생성일시, 수정일시 ) 분리!
---
BaseEntity를 추가했어요.
모든 Entity 클래스는 BaseEntity를 상속해서 사용해주세요.
---
> [SL-98] feat: BaseEntity 추가

- src/main/java/com/sds/actlongs/domain/BaseEntity.java
- src/main/java/com/sds/actlongs/infra/S3Uploader.java
- src/main/java/com/sds/actlongs/util/FileNameConstants.java
- src/main/resources/application-local.yml
- 리뷰 긴급도: D-1
S3에 동영상 업로드를 위한 S3Uploader 구현 및 관련 설정
---
- S3Uploeader 동영상 업로드 기능 추가
- application-local.yml multipart 관련 설정 추가
- FileNameConstants 추가
---
> [SL-24] S3Uploader 구현 및 관련 설정

- src/main/java/com/sds/actlongs/domain/video/entity/Video.java
- src/main/java/com/sds/actlongs/domain/video/respository/VideoRepository.java
- src/main/java/com/sds/actlongs/vo/VideoExtension.java
- src/test/java/com/sds/actlongs/domain/video/respository/VideoRepositoryTest.java
- 리뷰 긴급도: D-0
Video Entity 추가
* videos 테이블은 board_id를 외래키로 갖는다.
---
* Video Entity를 구성하고 Board와 일대일 Join 관계를 설정함.
* Harry 라는 멤버가 Knox SRE 채널에 동영상을 추가했을 때 잘 저장되는지 테스트하는 코드를 작성함.
---
> [SL-104] Video Entity 추가

- build.gradle
- src/main/java/com/sds/actlongs/infra/S3Downloader.java
- src/main/java/com/sds/actlongs/infra/S3Uploader.java
- src/main/java/com/sds/actlongs/util/Constants.java
- src/main/java/com/sds/actlongs/util/FileNameConstants.java
- 리뷰 긴급도: D-1
S3파일 다운로드 및 constants 파일 refactoring
---
S3Downloader 동영상 다운로드 기능 추가
분리되어있던 Constants 파일 통일
---
> [SL-24] feat: S3파일 다운로드 및 constants 파일 refactoring

- src/main/java/com/sds/actlongs/controller/member/MemberController.java
- src/main/java/com/sds/actlongs/controller/member/dto/LoginRequest.java
- src/main/java/com/sds/actlongs/controller/member/dto/MemberInfoResponse.java
- src/main/java/com/sds/actlongs/model/ErrorCode.java
- src/main/java/com/sds/actlongs/model/ResultCode.java
- 리뷰 긴급도: D-x
API 명세서 작성을 위한 Swagger 어노테이션 추가
---
---
> [SL-155] docs: 회원정보 조회 API Swagger 작성

- src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
- src/main/java/com/sds/actlongs/controller/channel/dto/ChannelCreateRequest.java
- src/main/java/com/sds/actlongs/controller/channel/dto/ChannelCreateResponse.java
- src/main/java/com/sds/actlongs/controller/member/MemberController.java
- src/main/java/com/sds/actlongs/model/ResultCode.java
- 리뷰 긴급도: D-x
API 명세서 작성을 위한 Swagger 어노테이션 추가
---
---
> [SL-163] docs: 그룹생성 API Swagger 작성

- src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
- src/main/java/com/sds/actlongs/controller/channel/dto/ChannelCreateRequest.java
- src/main/java/com/sds/actlongs/controller/channel/dto/ChannelCreateResponse.java
- 리뷰 긴급도: D-x
API 명세서 작성을 위한 Swagger 어노테이션 달기
---
* ResponseDTO 수정
* ResponseBody에서 그룹ID, 그룹명, 소유자ID 제거
---
> [SL-163] docs: 그룹생성 API Swagger 수정

- src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
- src/main/java/com/sds/actlongs/controller/channel/dto/ChannelResponse.java
- src/main/java/com/sds/actlongs/model/ResultCode.java
- 리뷰 긴급도: D-x
API 명세서 작성을 위한 Swagger 어노테이션 추가
---
---
> [SL-164] docs: 그룹목록 조회 API Swagger 작성

- src/main/java/com/sds/actlongs/config/WebConfig.java
- 리뷰 긴급도: D-x
쿠키 사용을 위해 설정 추가하기
---
상동
---
> [NO-ISSUE] 쿠키 관련 설정 추가

- src/main/java/com/sds/actlongs/config/WebConfig.java
- src/main/java/com/sds/actlongs/filter/AuthenticationFilter.java
- src/main/java/com/sds/actlongs/filter/CustomHttpServletResponseWrapper.java
- src/main/java/com/sds/actlongs/filter/LoginFilter.java
- src/main/java/com/sds/actlongs/util/Constants.java
- 리뷰 긴급도: D-1
fix: SameSite 및 Secure 속성을 JSESSIONID 쿠키로 설정
---
---
> [NO-ISSUE] fix: SameSite 및 Secure 속성을 JSESSIONID 쿠키로 설정

- src/main/java/com/sds/actlongs/config/WebConfig.java
- 리뷰 긴급도: D-x
dev환경 cors 설정 분리
---
---
> [NO-ISSUE] fix: dev환경 cors 설정 분리

- src/main/java/com/sds/actlongs/config/WebConfig.java
- 리뷰 긴급도: D-x
dev CORS originPatterns wildcard 적용 + credentials = true
---
---
> [NO-ISSUE] fix: dev CORS originPatterns wildcard 적용

- src/main/java/com/sds/actlongs/controller/member/MemberController.java
- src/main/java/com/sds/actlongs/controller/member/dto/MemberInfoResponse.java
- src/main/java/com/sds/actlongs/service/member/MemberService.java
- src/main/java/com/sds/actlongs/service/member/MemberServiceImpl.java
> [SL-156] feat: 회원정보 조회API 서비스 구현

- src/main/java/com/sds/actlongs/config/WebConfig.java
- src/main/java/com/sds/actlongs/filter/AuthenticationFilter.java
- 리뷰 긴급도: D-x
---
OPTIONS 요청은 인증 필터 로직 생략
exposedHeaders 추가
---
> [NO-ISSUE] fix: CORS 에러 해결

- src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
- src/main/java/com/sds/actlongs/controller/channel/dto/ChannelListResponse.java
- src/main/java/com/sds/actlongs/domain/channel/entity/Channel.java
- src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
- src/main/java/com/sds/actlongs/domain/member/entity/Member.java
- src/main/java/com/sds/actlongs/filter/AuthenticationFilter.java
- src/main/java/com/sds/actlongs/service/channel/ChannelService.java
- src/main/java/com/sds/actlongs/service/channel/ChannelServiceImpl.java
- src/test/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepositoryTest.java
- src/test/java/com/sds/actlongs/service/channel/ChannelServiceImplTest.java
- 리뷰 긴급도: D-1
그룹목록 조회 API 서비스 구현
> [SL-179] feat: 그룹목록 조회 API 서비스 구현

- build.gradle
- src/main/java/com/sds/actlongs/filter/AuthenticationFilter.java
- src/test/java/com/sds/actlongs/ActLongsApplicationTests.java
- 리뷰 긴급도: D-0
WebConfig 세팅 및 Security 세팅으로 인한 swagger/actuator 제한 + swagger version 숙지 미숙 => 안되는 현상 발생
---
build gradle 수정(종속성 수정) + authFilter에 해당 url 추가 + void contextLoads() 왜 있는지 모르고 에러 나서 제거
---
> [NO-ISSUE] Hotfix : swagger / actuator setting

- src/test/java/com/sds/actlongs/service/board/BoardServiceImplTest.java
> [SL-45] test: test code 수정

- src/main/java/com/sds/actlongs/controller/board/BoardController.java
- src/main/java/com/sds/actlongs/controller/board/dto/BoardListSearchResponse.java
- src/main/java/com/sds/actlongs/domain/video/repository/VideoRepository.java
- src/main/java/com/sds/actlongs/service/board/BoardService.java
- src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
- src/test/java/com/sds/actlongs/domain/video/repository/VideoRepositoryTest.java
- 리뷰 긴급도: D-x
게시글 제목 검색 API를 구현해요.
---
- JPQL로 쿼리 추가했어요.
---
> [SL-192] feat: 게시글 제목 검색 API 구현

- src/main/java/com/sds/actlongs/controller/channelmember/ChannelMemberController.java
- src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberListResponse.java
- src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
- src/main/java/com/sds/actlongs/domain/member/entity/Member.java
- src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberService.java
- src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImpl.java
- src/test/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepositoryTest.java
- 리뷰 긴급도: D-0
그룹원 목록 조회 API 구현
> [SL-187] 그룹원 목록 조회 API 구현

- src/main/java/com/sds/actlongs/domain/channel/entity/Channel.java
- src/main/java/com/sds/actlongs/domain/member/entity/Member.java
- src/main/java/com/sds/actlongs/domain/video/entity/Video.java
- src/main/resources/schema.sql
- 리뷰 긴급도: D-x
비티오 테이블 video_uuid, thumbnail_image_uuid 32자로 변경
---
---
> [SL-200] feat: 비디오 테이블 video_uuid, thumbnail_image_uuid 32자로 변경

- src/main/resources/schema.sql
- src/test/java/com/sds/actlongs/domain/video/repository/VideoRepositoryTest.java
- 리뷰 긴급도: D-x
uuid 32자 테스트 코드 변경
---
---
> [SL-200] test: uuid 32자 테스트 코드 변경

- src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
- src/main/java/com/sds/actlongs/domain/channel/entity/Channel.java
- src/main/java/com/sds/actlongs/domain/channel/repository/ChannelRepository.java
- src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
- src/main/java/com/sds/actlongs/service/channel/ChannelService.java
- src/main/java/com/sds/actlongs/service/channel/ChannelServiceImpl.java
- src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImpl.java
- src/main/resources/schema.sql
- src/test/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepositoryTest.java
- src/test/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImplTest.java
- 리뷰 긴급도: D-x
ㅈㄱㄴ
---
- 그룹에 속한 게시물들을 모두 삭제하는 것이 아닌, 상태만 deleted로 변경하는 방식으로 변경했어요.
---
> [SL-195] feat: 그룹 삭제 API 구현

- src/main/java/com/sds/actlongs/controller/board/dto/BoardDetailResponse.java
- src/main/java/com/sds/actlongs/controller/board/dto/BoardDto.java
- src/main/java/com/sds/actlongs/util/Constants.java
- 리뷰 긴급도: D-1
썸네일 uuid를 url로 변경
---
게시글 조회시 썸네일 uuid를 url로 받을수 있게 변경
---
> [SL-219] feat: 썸네일 uuid를 url로 변경

- src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberListResponse.java
- 리뷰 긴급도: D-x
ㅈㄱㄴ
---
응답 모델에 pk 추가했어요~
---
> [NO-ISSUE] feat: 그룹 회원 목록 조회 API 응답 모델 수정

- src/main/java/com/sds/actlongs/domain/board/entity/Board.java
- src/main/java/com/sds/actlongs/domain/board/repository/BoardRepository.java
- src/main/java/com/sds/actlongs/domain/channel/entity/Channel.java
- src/main/java/com/sds/actlongs/domain/video/repository/VideoRepository.java
- src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
- src/main/resources/schema.sql
> [NO-ISSUE] Board column 추가(status) 및 리팩토링

- src/main/resources/data.sql
- 리뷰 긴급도: D-x
dummy data 추가 sql 작성
---
---
> [NO-ISSUE] chore: dummy data 추가 sql 작성

- src/main/java/com/sds/actlongs/controller/channelmember/ChannelMemberController.java
- src/main/java/com/sds/actlongs/controller/channelmember/dto/ChannelLeaveResponse.java
- src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberInviteRequest.java
- src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberInviteResponse.java
- src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
- src/main/java/com/sds/actlongs/model/ResultCode.java
- src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberService.java
- src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImpl.java
- 리뷰 긴급도: D-0
* SL-194 : 그룹원 초대 API 구현 (브랜치 꼬여서 feature/SL-226에서 한번에 추가함)
* SL-226 : 그룹 탈퇴 API 구현
---
* 그룹 탈퇴 시 세션에 저장되어 있는 그룹 목록도 업데이트 함.
> [SL-226] 그룹원 초대, 그룹 탈퇴 API 구현

- src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
- src/main/java/com/sds/actlongs/controller/channel/dto/ChannelListResponse.java
- src/main/java/com/sds/actlongs/domain/channel/repository/ChannelRepository.java
- src/main/java/com/sds/actlongs/service/channel/ChannelService.java
- src/main/java/com/sds/actlongs/service/channel/ChannelServiceImpl.java
- src/test/java/com/sds/actlongs/service/channel/ChannelServiceImplTest.java
- 리뷰 긴급도: D-x
session mocking 번거로움으로 테스트 코드 주석처리
> [SL-227] 세션에 저장된 그룹 목록 업데이트
